// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.ViewModels.ItemsViewModel.LoadItemsAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.DataAccess.Items.GetItemsAsync~System.Threading.Tasks.Task{Packit.Model.Item[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.Views.ItemsPage.ItemsPage_LoadedAsync(System.Object,Windows.UI.Xaml.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.DataAccess.GenericDataAccess`1.GetAll(System.String)~System.Threading.Tasks.Task{`0[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.DataAccess.GenericDataAccess`1.Delete(`0,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.DataAccess.GenericDataAccess`1.Add(`0,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.DataAccess.GenericDataAccess`1.GetImage(System.String)~System.Threading.Tasks.Task{Windows.UI.Xaml.Controls.Image}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.DataAccess.GenericDataAccess`1.GetImage(System.Int32)~System.Threading.Tasks.Task{Windows.UI.Xaml.Media.Imaging.BitmapImage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.DataAccess.GenericDataAccess`1.GetImage(System.String)~System.Threading.Tasks.Task{Windows.UI.Xaml.Media.Imaging.BitmapImage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Packit.App.ViewModels.ItemsViewModel.LoadImages~System.Threading.Tasks.Task")]
